### ISSUE TITLE
Node executable doesn't support python 3

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#100]
Possible reason to not add python to installfest. via @gaand

**Comment by jrhorn424** [comment]
@J-Weeks _Please_ provide better descriptions of your issues. I don't know why Node should care about Python for the lessons on Python.

**Comment by gaand** [comment]
npm uses Python when building native modules. 

Not an issue if the default for Python is 2.7.x (native or global from pyenv).

**Comment by raq929** [comment]
Is there a reason we're not using `pip` and `virtualenv` for Python installs?

**Comment by jrhorn424** [comment]
> Is there a reason we're not using pip and virtualenv for Python installs?

That's tangential to the issue at hand. See  my comments in #95.

@gaand Default for python on macOS factory installs is still `2.7`. And `brew` links `python2` to `python` automatically as well (as opposed to `python3`). Is this therefore closable?

**Comment by gaand** [comment]
@raq929 Yes.  See https://github.com/yyuu/pyenv 

@jrhorn424 This came up because we gave them a day on python (3) and `pyenv` should be used with `.python-version` keeping the global at 2.7.  So, is it closeable?  I think it depends on changing to a JIT and getting making the settings right.  Unless we're never going to teach python.

**Comment by jrhorn424** [comment]
@gaand I am in favor of closing. If it comes up again, there will likely be a better place to track it.
