### ISSUE TITLE
Can hub be installed through linuxbrew?

### ISSUE THREAD

**Issue by payne-chris-r** [ga-wdi-boston/orientation#156]
Do Linux users need `Hub`? If so, is this the correct documentation to follow? https://hub.github.com/

**Comment by berziiii** [comment]
In attempt on Jacobs ubuntu computer, ruby-build failed but every other brew command ran successfully. Address with more time to dedicate?

**Comment by gaand** [comment]
@berziiii @jrhorn424 Do we have a commit or other indication of the resolution?

**Comment by jrhorn424** [comment]
This issue is unresolved. It (was) one of the confusing sections of the README that seemed to indicate only one type of OS needed the tool.

Additionally, when this failed in 012, IIRC, it was because we were attempting to install `hub` with linuxbrew, and it failed.

The compiling instructions or binaries should suffice. However, `brew install go` is necessary if compiling from source.

**Comment by raq929** [comment]
The question is, do we need different instructions for linux.

**Comment by scottyscripts** [comment]
moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/156
