### ISSUE TITLE
Remove instructions to modify `/etc/paths`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/orientation#182]
Changes in brew's requirements to operate successfully.

**Comment by jrhorn424** [comment]
@gaand Do you have a link to what changed, or can you elaborate a bit more? Thanks.

**Comment by raq929** [comment]
I think the upgrade to OSX Sierra rendered the path change unnecessary.

**Comment by jrhorn424** [comment]
> I believe this step is no longer necessary. (@gaand via #202)

True, no longer required for homebrew.

For Finder-launched applications, `/etc/paths` used to be the canonical way to set the correct PATH. This was particularly important in the early days of SublimeText. Here's the original reference I found to fix: http://superuser.com/questions/69130/where-does-path-get-set-in-os-x-10-6-snow-leopard

This issue arises because macOS handles its environment differently than BSD or Linux. They have a proprietary set of tools that aren't in *nix-like systems (like `setenv`, `launchctl`, and `defaults`). (As an aside, macOS also uses the `/etc/paths` file first and then loads anything in `/etc/paths.d`, which is initially empty.)

I also found a new, different fix, that may be more palatable to @gaand: edit the shell configuration files for macOS machines to use `setenv` instead of editing `/etc/paths`. Source: http://apple.stackexchange.com/a/51678/34225

**Comment by jrhorn424** [comment]
As @raq929 noted in #202, Apple has made our changes the default: http://apple.stackexchange.com/questions/215697/what-is-the-default-content-in-private-etc-paths

It might still be a good idea to use `launchctl setenv` to set the `PATH` as a final step in the shell configuration file, since we make other slight changes to the `PATH` for the shell.

**Comment by jrhorn424** [comment]
> It might still be a good idea to use launchctl setenv to set the PATH as a final step in the shell configuration file, since we make other slight changes to the PATH for the shell.

I retract this statement.

**Comment by scottyscripts** [comment]
Moved to and closed on GHE https://git.generalassemb.ly/ga-wdi-boston/orientation/issues/182
