### ISSUE TITLE
Consider switching to atom

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#28]
`atom` has the same keyboard shortcuts as sublime, but it has the advantage of being open-source, so no nag screens. There's package parity for the packages we use as well.

**Comment by gaand** [comment]
If we reach consensus I'll switch, but I actually find atom slow and annoying.

Since I override sublime's keybindings with an emacsify package, that's not an argument for me :-P. Especially since atom doesn't implement basic behaviors that are in my hands from emacs.

None of which should stop us from switching :-).

**Comment by jrhorn424** [comment]
Wanna teach emacs? ;)

BTW, the readline packaged with OSX is available in almost all text inputs. So, you shouldn't need an emacs package for emacs-like navigation line-wise, killing, etc.

I'll leave this open but I don't think it's a high priority.

**Comment by gaand** [comment]
As I mentioned, the problem is atom on linux (ctrl does double duty both ctrl and command).  So, I'm okay with switching for the next cohort.  Although, that does require that we vet various packages for atom.

**Comment by jrhorn424** [comment]
Have you used it at any length? I remember it being a bit resource intensive in the past.

I dunno why I have it out for Sublime so bad. I used it for years.

**Comment by gaand** [comment]
I'm using it almost exclusively at this point.  I hadn't considered the resource overhead.  Is this something we need to consider for students?
