### ISSUE TITLE
Document icebreaker activity instructions

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#52]
Two truths and a lie

**Comment by berziiii** [comment]
- 'Developer's write 3 interesting facts on the lined side of 3x5 index card
- Two of the facts are true and one of the facts is a lie
- Intent is that the lie could be true and that the truths could be perceived as a lie
- Cards are collected, shuffled and passed back out to 'developers'; 'developers' should not have their own card in their hand
- Choose random 'developer' to start and have them read the facts on the card they hold
- They have 2 guesses to indentify whos card they hold
- After 2 guess, if not correct, actual developer identifies themselves
- Then person holding card has 2 guesses to try and choose the lie
- Highlight which fact is the lie and put name of the 'developer' who wrote the card is put on blank side of the index card
- 'Developer' who had their card read, goes next; continues until all cards are read and 'developers' identified
- Deck is used to random cold calling purpose since the cards have all 'developer' names on it

**Comment by jrhorn424** [comment]
This is good. One small change. Please use fake names (one male and one female) in examples instead of 'developer'.
