### ISSUE TITLE
Add instructions to install linters to Sublime Text

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/orientation#8]

**Comment by GA-MEB** [comment]
There's a bit of a dependency issue in that we probably want Sublime up front so that students can more easily edit their config files, but I'm not sure if installing the linters will work unless the actual modules/gems are already installed. We should test this. Of course, if it doesn't work, we can always double back to Sublime.

**Comment by jrhorn424** [comment]
OBE. Initial linters have been added for atom.
