### ISSUE TITLE
linux dev tools missing

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/orientation#86]
for ruby, need to add.  (possibly removed?)

**Comment by jrhorn424** [comment]
@J-Weeks Please provide more data. I'm not sure which packages are needed from aptitude.

**Comment by jrhorn424** [comment]
@ga-wdi-boston/core Anyone have any data on this?

This isn't English.

> for ruby, need to add. (possibly removed?)

**Comment by RealWeeks** [comment]
We had instructions for special linux dev tools that were in the installfest repo. If I remember correctly they were deemed unnecessary and removed without this issue being closed.

**Comment by raq929** [comment]
We now are now using Homebrew for linux. Can this be closed?

**Comment by jrhorn424** [comment]
The current README includes devtools. This issue arose because of the `watchman` dependency for `ember-cli`. https://facebook.github.io/watchman/docs/install.html#installing-from-source

I'm going to close this in favor of posting an exact manifest for `brew install <whatever>` if there are issues in 016.
